#!groovy

// Generated by IBM TransformationAdvisor
// Tue Nov 20 16:41:52 EST 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytraderee6'
    mvnCommands = '-X initialize process-resources verify'
    test='false'
}