#!groovy

// Generated by IBM TransformationAdvisor
// Fri Nov 02 17:57:02 EDT 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytraderee6'
    mvnCommands = '-X initialize process-resources verify'
    test='false'
}