#!groovy

// Generated by IBM TransformationAdvisor
// Tue Nov 06 11:32:43 EST 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytraderee6'
    mvnCommands = '-X initialize process-resources verify'
    test='false'
}